# Generated by Django 2.1.7 on 2019-04-28 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190427_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applying_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Applicant')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Internship')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Job')),
            ],
        ),
    ]
