# Generated by Django 2.1.7 on 2019-04-28 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_applications_applying_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_conducted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('interview_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('status', models.CharField(max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Applicant')),
                ('hr_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hr_Manger')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Interview')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='descriptions',
            field=models.CharField(max_length=100),
        ),
    ]
