# Generated by Django 2.1.7 on 2019-04-28 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190428_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('offer_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('interview_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('status', models.CharField(max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Applicant')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Internship')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Job')),
            ],
        ),
    ]
